-- Caver Cat demo products
-- Safe to run multiple times due upsert on slug.

insert into public.products (
  name,
  slug,
  description,
  price_cents,
  category,
  image_url,
  stock_quantity,
  is_active,
  is_handmade,
  recycled_material_percentage,
  sustainability_tags
)
values
  (
    'Echo Pack 30L',
    'echo-pack-30l',
    'Hand-stitched cave pack with abrasion panels and modular anchor loops.',
    18900,
    'Packs',
    'https://images.unsplash.com/photo-1526178613658-3f1622045557?auto=format&fit=crop&w=1200&q=80',
    18,
    true,
    true,
    90,
    array['Handmade','90% recycled materials','Cave-conscious gear','Locally owned']
  ),
  (
    'Hollow Ridge Rope Bag',
    'hollow-ridge-rope-bag',
    'Rope carry bag designed for muddy descents and quick deployment at anchors.',
    9900,
    'Rope & Rigging',
    'https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?auto=format&fit=crop&w=1200&q=80',
    24,
    true,
    true,
    90,
    array['Handmade','90% recycled materials','Limited run']
  ),
  (
    'Lantern Trail Utility Pouch',
    'lantern-trail-utility-pouch',
    'Compact pouch for batteries, small tools, and emergency signal markers.',
    4200,
    'Accessories',
    'https://images.unsplash.com/photo-1555529771-835f59fc5efe?auto=format&fit=crop&w=1200&q=80',
    36,
    true,
    true,
    92,
    array['Handmade','90% recycled materials','Cave-conscious gear']
  ),
  (
    'Stalactite Field Tote',
    'stalactite-field-tote',
    'Reinforced daily carry tote for urban-to-trail transitions.',
    5600,
    'Bags',
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
    42,
    true,
    true,
    95,
    array['Handmade','90% recycled materials','Locally owned']
  ),
  (
    'Blackstone Caving Gloves',
    'blackstone-caving-gloves',
    'Grip-forward gloves with durable palms for rope and rock contact.',
    6400,
    'Gloves',
    'https://images.unsplash.com/photo-1589739900243-4b52cd9ddf6b?auto=format&fit=crop&w=1200&q=80',
    40,
    true,
    false,
    65,
    array['Cave-conscious gear']
  ),
  (
    'Descent Dry Bag',
    'descent-dry-bag',
    'Roll-top dry bag tuned for wet cave passages and spring routes.',
    7300,
    'Bags',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    28,
    true,
    true,
    90,
    array['Handmade','90% recycled materials','Conservation-minded']
  ),
  (
    'Cave Map Case',
    'cave-map-case',
    'Water-sealed map sleeve with low-glare window and strap points.',
    3400,
    'Navigation',
    'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
    52,
    true,
    true,
    90,
    array['Handmade','90% recycled materials']
  ),
  (
    'Recycled Gear Roll',
    'recycled-gear-roll',
    'Organized roll for pitons, small hardware, and emergency repair tools.',
    5100,
    'Storage',
    'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1200&q=80',
    33,
    true,
    true,
    94,
    array['Handmade','90% recycled materials','Limited run']
  ),
  (
    'Underground First Aid Kit',
    'underground-first-aid-kit',
    'Compact first aid kit shell tailored for humid underground travel.',
    8600,
    'Safety',
    'https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=1200&q=80',
    20,
    true,
    false,
    40,
    array['Cave-conscious gear','Conservation-minded']
  ),
  (
    'Ember Headlamp Strap',
    'ember-headlamp-strap',
    'Replaceable headlamp strap made from upcycled webbing.',
    1900,
    'Lighting',
    'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    80,
    true,
    true,
    96,
    array['Handmade','90% recycled materials','Locally owned']
  ),
  (
    'Karst Climber Chalk Bag',
    'karst-climber-chalk-bag',
    'Handmade chalk bag with recycled lining and cave-cat crest patch.',
    4400,
    'Climbing',
    'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80',
    29,
    true,
    true,
    90,
    array['Handmade','90% recycled materials','Limited run']
  ),
  (
    'Moonmilk Camp Mug',
    'moonmilk-camp-mug',
    'Enamel mug with Caver Cat print for post-expedition camp mornings.',
    2800,
    'Camp',
    'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=80',
    64,
    true,
    false,
    20,
    array['Locally owned']
  ),
  (
    'Bat Habitat Support Patch',
    'bat-habitat-support-patch',
    'Support patch item linked to future bat habitat preservation funds.',
    1500,
    'Mission',
    'https://images.unsplash.com/photo-1517456793572-1d5fef6ab4dd?auto=format&fit=crop&w=1200&q=80',
    120,
    true,
    true,
    92,
    array['Conservation-minded','90% recycled materials','Locally owned']
  ),
  (
    'Low-Impact Explorer Kit',
    'low-impact-explorer-kit',
    'Bundle with recycled pouch, map case, and trail clean-up accessories.',
    13900,
    'Kits',
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    14,
    true,
    true,
    91,
    array['Handmade','90% recycled materials','Conservation-minded']
  ),
  (
    'Recycled Trail Snack Pouch',
    'recycled-trail-snack-pouch',
    'Reusable snack pouch with easy-clean lining for long approaches.',
    2200,
    'Accessories',
    'https://images.unsplash.com/photo-1499696010180-025ef4f96de7?auto=format&fit=crop&w=1200&q=80',
    70,
    true,
    true,
    93,
    array['Handmade','90% recycled materials']
  ),
  (
    'Handmade Recycled Cave Pack',
    'handmade-recycled-cave-pack',
    'Field pack emphasizing vertical carry comfort and abrasion resistance.',
    17600,
    'Packs',
    'https://images.unsplash.com/photo-1517343985841-f8b2d66e010b?auto=format&fit=crop&w=1200&q=80',
    17,
    true,
    true,
    90,
    array['Handmade','90% recycled materials','Cave-conscious gear']
  ),
  (
    'Recycled Rope Bag',
    'recycled-rope-bag',
    'Recycled nylon rope bucket with drain vents and clip loops.',
    8800,
    'Rope & Rigging',
    'https://images.unsplash.com/photo-1543357480-c60d40007a3f?auto=format&fit=crop&w=1200&q=80',
    31,
    true,
    true,
    90,
    array['Handmade','90% recycled materials']
  ),
  (
    'Waterproof Field Notebook',
    'waterproof-field-notebook',
    'Weatherproof notebook for cave notes, route logs, and survey checkpoints.',
    2100,
    'Navigation',
    'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=1200&q=80',
    90,
    true,
    false,
    0,
    array['Cave-conscious gear']
  ),
  (
    'Carabiner Set',
    'carabiner-set',
    'Five-pack locking carabiner kit for anchor and camp utility.',
    5700,
    'Hardware',
    'https://images.unsplash.com/photo-1521503862198-2ae9a997bbc9?auto=format&fit=crop&w=1200&q=80',
    66,
    true,
    false,
    15,
    array['Cave-conscious gear']
  ),
  (
    'First Aid Kit',
    'first-aid-kit',
    'Basic field medical pouch with rugged shell and internal organization.',
    4900,
    'Safety',
    'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1200&q=80',
    48,
    true,
    false,
    25,
    array['Conservation-minded']
  ),
  (
    'Dry Bag',
    'dry-bag',
    'Lightweight roll-top bag for wet sections and stream crossings.',
    3900,
    'Bags',
    'https://images.unsplash.com/photo-1465310477141-6fb93167a273?auto=format&fit=crop&w=1200&q=80',
    57,
    true,
    false,
    30,
    array['Cave-conscious gear']
  ),
  (
    'Conservation Support Item',
    'conservation-support-item',
    'Mission-forward purchase placeholder supporting future cave initiatives.',
    1200,
    'Mission',
    'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
    200,
    true,
    true,
    90,
    array['Conservation-minded','90% recycled materials']
  ),
  (
    'Recycled Gear Pouch',
    'recycled-gear-pouch',
    'Utility pouch made from repurposed expedition fabric offcuts.',
    2600,
    'Storage',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
    75,
    true,
    true,
    95,
    array['Handmade','90% recycled materials','Locally owned']
  ),
  (
    'Packable Rain Shell',
    'packable-rain-shell',
    'Packable shell layer for wet approaches and cave entrance weather shifts.',
    12900,
    'Apparel',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
    22,
    true,
    false,
    55,
    array['Cave-conscious gear']
  ),
  (
    'Exploration Patch',
    'exploration-patch',
    'Limited run embroidered patch for community field teams.',
    1300,
    'Mission',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    150,
    false,
    true,
    92,
    array['Limited run','Conservation-minded','90% recycled materials']
  ),
  (
    'Camp Mug with Logo',
    'camp-mug-with-logo',
    'Logo camp mug for basecamp brews before early descent starts.',
    2400,
    'Camp',
    'https://images.unsplash.com/photo-1459755486867-b55449bb39ff?auto=format&fit=crop&w=1200&q=80',
    92,
    true,
    false,
    10,
    array['Locally owned']
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price_cents = excluded.price_cents,
  category = excluded.category,
  image_url = excluded.image_url,
  stock_quantity = excluded.stock_quantity,
  is_active = excluded.is_active,
  is_handmade = excluded.is_handmade,
  recycled_material_percentage = excluded.recycled_material_percentage,
  sustainability_tags = excluded.sustainability_tags,
  updated_at = timezone('utc', now());
